source 'http://rubygems.org'

gem 'decent_exposure'
gem 'fabrication'
gem 'haml'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '3.1.1'
gem 'responders'

group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'dirty'
  gem 'email_spec'
  gem 'fuubar'
  gem 'fuubar-cucumber'
  gem 'itslog'
  gem 'launchy'
  gem 'pickler'
  gem 'rspec-rails'
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'shoulda-matchers'
end
